//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestin.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gestin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap advertencia {
            get {
                object obj = ResourceManager.GetObject("advertencia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;/meta&gt;@META
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;&lt;/meta&gt;@META
        ///    &lt;title&gt;Analitico parcial&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;font-family: Arial, sans-serif;&quot;&gt;
        ///    &lt;table style=&quot;width: 100%; height: auto; margin: auto; padding: 10px;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;img src=&quot;@RUTA&quot; id=&quot;img&quot; alt=&quot;Logo&quot; style=&quot;margin-left: 10px; width: 200px;&quot;&gt;&lt;/img&gt;@IMG
        ///            &lt;/td&gt;
        ///            [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string analiticoParcial2 {
            get {
                return ResourceManager.GetString("analiticoParcial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!--studentDataRowStart--&gt;
        ///&lt;tr class=&quot;studentDataRow&quot;&gt;
        ///    &lt;td class=&quot;orderCountRow&quot;&gt;@studentCount&lt;/td&gt;
        ///    &lt;td class=&quot;orderRow&quot;&gt;@enrolledStudent&lt;/td&gt;
        ///    &lt;td class=&quot;dateModule&quot;&gt;&lt;!--@AcademicStatus--&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;dateModule&quot;&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;dateModule&quot;&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;dateModule&quot;&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;dateModule&quot;&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;dateModule&quot;&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;dateModule&quot;&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;dateModule&quot;&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;dateModule&quot;&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;dateModule&quot;&gt;&lt;/ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string AsistenciaStudentRow {
            get {
                return ResourceManager.GetString("AsistenciaStudentRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///&lt;style&gt;
        ///    table {
        ///        width: 100%;
        ///    }
        ///
        ///    td {
        ///        font-size: 11.5px;
        ///        border: 1px solid;
        ///    }
        ///
        ///    th {
        ///        font-size: 11.5px;
        ///        text-align: center;
        ///        width: 80px;
        ///    }
        ///
        ///    .upper {
        ///        width: 0px;
        ///    }
        ///
        ///    .middle {
        ///        width: 320px;
        ///    }
        ///
        ///    .lower {
        ///        width: 0px;
        ///    }
        ///
        ///    .academicStateTitle {
        ///        width: 30px;
        ///    }
        ///
        ///    .dateTitle {
        ///        text-align: center;
        ///        width: 50px;
        ///    }
        ///
        ///    .studentN [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string AsistenciaStyles {
            get {
                return ResourceManager.GetString("AsistenciaStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;dateModuleGrayed&quot;&gt;&lt;/td&gt;
        ///        &lt;td class=&quot;dateModuleGrayed&quot;&gt;&lt;/td&gt;
        ///        &lt;td class=&quot;dateTitle&quot; style=&quot;font-size:8px&quot;&gt;FECHA&lt;/td&gt;
        ///        &lt;td class=&quot;date&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/td&gt;
        ///        &lt;td class=&quot;date&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/td&gt;
        ///        &lt;td class=&quot;date&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/td&gt;
        ///        &lt;td class=&quot;date&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/td&gt;
        ///        &lt;td class=&quot;date&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/td&gt;
        ///        &lt;td class=&quot;date&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/td&gt;
        ///      [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string AsistenciaTemplateBody {
            get {
                return ResourceManager.GetString("AsistenciaTemplateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///&lt;table&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;libreRowTitle&quot;&gt;Estudiantes Libres&lt;/td&gt;
        ///        &lt;td class=&quot;libreRow&quot;&gt;@libreStudentList&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///
        ///
        ///&lt;table&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;infoRow&quot;&gt;Estado: (A) Atraso académico - (R) Recursante&lt;/td&gt;
        ///        &lt;td class=&quot;infoRow&quot;&gt;Importante : se debe ingresar P (presente), A (ausente) o AJ (ausente justificado, con presentación del certificado correspondiente&lt;/td&gt;
        ///        &lt;td class=&quot;infoRow&quot;&gt;Tener en cuenta que la asistencia se debe consignar por HORA&lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string AsistenciaTemplateFooter {
            get {
                return ResourceManager.GetString("AsistenciaTemplateFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///    &lt;table style= &quot;border: none; width: 100%;&quot;&gt;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;table style=&quot;font-size:8px; width: 37%;&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;th rowspan=&quot;3&quot;&gt;Horarios&lt;/th&gt;
        ///                        &lt;th&gt;Lunes&lt;/th&gt;
        ///                        &lt;th&gt;Martes&lt;/th&gt;
        ///                        &lt;th&gt;Miércoles&lt;/th&gt;
        ///                        &lt;th&gt;Jueves&lt;/th&gt;
        ///                        &lt;th&gt;Viernes&lt;/th&gt;
        ///                        &lt;th&gt;Sábado&lt;/th&gt;
        ///                    &lt;/tr&gt;
        ///            [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string AsistenciaTemplateHeader {
            get {
                return ResourceManager.GetString("AsistenciaTemplateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigErrorIcon {
            get {
                object obj = ResourceManager.GetObject("BigErrorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Carreras {
            get {
                object obj = ResourceManager.GetObject("Carreras", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CerraSesion {
            get {
                object obj = ResourceManager.GetObject("CerraSesion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;/meta&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;&lt;/meta&gt;
        ///    &lt;title&gt;Plantilla certificado&lt;/title&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;font-family: Arial, sans-serif;&quot;&gt;
        ///    &lt;table style=&quot;  width: 100%; height: auto; margin: auto; padding: 10px; border: 1px black solid;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;padding:20px;&quot;&gt;
        ///                &lt;img style=&quot;margin-left: 20px; width: 300px;&quot; id=&quot;imagen&quot; src=&quot;@RUTA&quot; alt=&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string certificado {
            get {
                return ResourceManager.GetString("certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloudError {
            get {
                object obj = ResourceManager.GetObject("CloudError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap databaseIcon {
            get {
                object obj = ResourceManager.GetObject("databaseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteIcon {
            get {
                object obj = ResourceManager.GetObject("deleteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Done {
            get {
                object obj = ResourceManager.GetObject("Done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Email {
            get {
                object obj = ResourceManager.GetObject("Email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enrolmentIcon {
            get {
                object obj = ResourceManager.GetObject("enrolmentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorSmall {
            get {
                object obj = ResourceManager.GetObject("ErrorSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExamIcon {
            get {
                object obj = ResourceManager.GetObject("ExamIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eye {
            get {
                object obj = ResourceManager.GetObject("Eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gearIcon {
            get {
                object obj = ResourceManager.GetObject("gearIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home2 {
            get {
                object obj = ResourceManager.GetObject("Home2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Index {
            get {
                object obj = ResourceManager.GetObject("Index", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ITEC_194 {
            get {
                object obj = ResourceManager.GetObject("ITEC_194", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrowIcon {
            get {
                object obj = ResourceManager.GetObject("LeftArrowIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoadingGif {
            get {
                object obj = ResourceManager.GetObject("LoadingGif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimize {
            get {
                object obj = ResourceManager.GetObject("Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Password {
            get {
                object obj = ResourceManager.GetObject("Password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Profile {
            get {
                object obj = ResourceManager.GetObject("Profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reporte {
            get {
                object obj = ResourceManager.GetObject("reporte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StudentIcon {
            get {
                object obj = ResourceManager.GetObject("StudentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap subjectIcon {
            get {
                object obj = ResourceManager.GetObject("subjectIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TickIcon {
            get {
                object obj = ResourceManager.GetObject("TickIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
